#!/bin/bash

MAX_DEPTH=$1
if [[ $MAX_DEPTH == '' ]]; then
	MAX_DEPTH=1
fi

find . -maxdepth $MAX_DEPTH -type d -print0 | sort -z | \
while IFS= read -r -d '' i ; do \
echo -n "$i: " ; (find "$i" -type f | wc -l) ; done
