#!/bin/bash

today=$(date +"%Y-%m-%d")
tomorrow=$(gdate -d "tomorrow" '+%Y-%m-%d')
yesterday=$(gdate -d "yesterday" '+%Y-%m-%d')
file="$VAULT"'/notes/diary/'$(date +"%Y-%m-%d").md

cd "$VAULT" || exit

new_note() {
	touch "$file"

	# Format the file with the daily template
	# TODO: make aliases field same as Obsidian notes. Same with first title
	cat <<EOF >"$file"
---
id: "$today"
aliases:
  - "$today"
tags:
  - daily-notes
---

# $today

[[$yesterday]] - [[$tomorrow]]

## Intention

What do I want to achieve today and tomorrow?

## Tracking

- [ ] Meditation
- [ ] Yoga or stretching exercise
- [ ] Answer 1 question
- [ ] Skin routine
- [ ] Oral routine

- [ ] Check tasks backlog

## Log
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
	echo "File does not exist, creating new daily note."
	new_note
fi

# Open the daily note at the bottom of the file in insert mode 
nvim '+ normal Gzzo' "$file"
