#!/bin/bash
# ~~~~~~~~~~~~~~~ Welcome Screen :) ~~~~~~~~~~~~~~~~~~~~~~~~
# taken from TJDevries's config repo
clear
C='\033[1;36m'
R="\033[31m"
G="\033[32m"
Y="\033[33m"
RESET="\033[m"

echo -ne "${Y}Hello, $USER. Today is: " 
date
echo -ne "${RESET}"
echo -e "${G}"
cal
echo -ne "${RESET}"
echo
echo -ne "${Y}Sysinfo: "
uptime
echo -e "${RESET}"
