#!/bin/bash

# A bash script that helps the creation of notes
# Taken from mischavandenburg (and added minor modifications)

# function to prompt the user for a filename
get_filename() {
	read -r -p "Enter a filename: " filename
	echo "$filename"
}

# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit

	# Check if file already exists
	if [[ -f "$1/$filename.md" ]]; then
		#echo "A file with the entered filename already exists. Try a different name."
		echo "A file with the entered filename already exists. Opening it..."
		nvim "$1/$filename.md"
		exit 55
	fi

	# Create the file in the specified directory
	touch "$1/$filename.md"

	# create unique identifier and links section
	timestamp="$(date +"%Y%m%d%H%m")"

	# format the file
	{
		echo "# "
		echo -en "\n"
		echo -en "\n"
		echo -en "\n"
		echo "Links:"
		echo -en "\n"
		echo "$timestamp"
	} >>"$1/$filename.md"

	# Open the file in Neovim
	nvim '-c normal ggA' "$1/$filename.md"
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file "$VAULT/0-inbox"
